export interface RegionChild {
  /** 화면에 표시되는 이름 */
  label: string;
  /** 백엔드에 전달하는 실제 행정구역명 배열 (빈 배열이면 해당 시/도 전체) */
  values: string[];
  /**
   * 전국 자식 아이템 전용
   * - null: 전국 전지역 (depth1도 null로 전달)
   * - string: 해당 시/도 전체 선택 시 사용할 depth1 값
   */
  regionValue?: string | null;
}

export interface Region {
  /** 화면에 표시되는 시/도 이름 */
  label: string;
  /** 실제 시/도 행정구역명 */
  value: string;
  children: RegionChild[];
}

/**
 * 전국 행정구역 데이터
 *
 * [백엔드 전달 방식]
 * { depth1: Region.value, depth2: RegionChild.values }
 *
 * [백엔드 쿼리 분기]
 * depth2가 빈 배열 → WHERE 시도 = :depth1          (전지역)
 * depth2가 있음    → WHERE 시도 = :depth1 AND 시 IN (:depth2)
 */
export const REGIONS: Region[] = [
  {
    label: "전국",
    value: "전국",
    children: [
      { label: "전국 전지역", values: [], regionValue: null },
      { label: "서울", values: [], regionValue: "서울특별시" },
      { label: "부산", values: [], regionValue: "부산광역시" },
      { label: "대구", values: [], regionValue: "대구광역시" },
      { label: "인천", values: [], regionValue: "인천광역시" },
      { label: "광주", values: [], regionValue: "광주광역시" },
      { label: "대전", values: [], regionValue: "대전광역시" },
      { label: "울산", values: [], regionValue: "울산광역시" },
      { label: "세종", values: [], regionValue: "세종특별자치시" },
      { label: "경기", values: [], regionValue: "경기도" },
      { label: "강원", values: [], regionValue: "강원특별자치도" },
      { label: "충북", values: [], regionValue: "충청북도" },
      { label: "충남", values: [], regionValue: "충청남도" },
      { label: "전북", values: [], regionValue: "전북특별자치도" },
      { label: "전남", values: [], regionValue: "전라남도" },
      { label: "경북", values: [], regionValue: "경상북도" },
      { label: "경남", values: [], regionValue: "경상남도" },
      { label: "제주", values: [], regionValue: "제주특별자치도" },
    ],
  },
  {
    label: "서울",
    value: "서울특별시",
    children: [
      { label: "서울 전지역", values: [] },
      { label: "강남구", values: ["강남구"] },
      { label: "강동구", values: ["강동구"] },
      { label: "강북구", values: ["강북구"] },
      { label: "강서구", values: ["강서구"] },
      { label: "관악구", values: ["관악구"] },
      { label: "광진구", values: ["광진구"] },
      { label: "구로구", values: ["구로구"] },
      { label: "금천구", values: ["금천구"] },
      { label: "노원구", values: ["노원구"] },
      { label: "도봉구", values: ["도봉구"] },
      { label: "동대문구", values: ["동대문구"] },
      { label: "동작구", values: ["동작구"] },
      { label: "마포구", values: ["마포구"] },
      { label: "서대문구", values: ["서대문구"] },
      { label: "서초구", values: ["서초구"] },
      { label: "성동구", values: ["성동구"] },
      { label: "성북구", values: ["성북구"] },
      { label: "송파구", values: ["송파구"] },
      { label: "양천구", values: ["양천구"] },
      { label: "영등포구", values: ["영등포구"] },
      { label: "용산구", values: ["용산구"] },
      { label: "은평구", values: ["은평구"] },
      { label: "종로구", values: ["종로구"] },
      { label: "중구", values: ["중구"] },
      { label: "중랑구", values: ["중랑구"] },
    ],
  },
  {
    label: "부산",
    value: "부산광역시",
    children: [
      { label: "부산 전지역", values: [] },
      { label: "강서구", values: ["강서구"] },
      { label: "금정구", values: ["금정구"] },
      { label: "기장군", values: ["기장군"] },
      { label: "남구", values: ["남구"] },
      { label: "동구", values: ["동구"] },
      { label: "동래구", values: ["동래구"] },
      { label: "부산진구", values: ["부산진구"] },
      { label: "북구", values: ["북구"] },
      { label: "사상구", values: ["사상구"] },
      { label: "사하구", values: ["사하구"] },
      { label: "서구", values: ["서구"] },
      { label: "수영구", values: ["수영구"] },
      { label: "연제구", values: ["연제구"] },
      { label: "영도구", values: ["영도구"] },
      { label: "중구", values: ["중구"] },
      { label: "해운대구", values: ["해운대구"] },
    ],
  },
  {
    label: "대구",
    value: "대구광역시",
    children: [
      { label: "대구 전지역", values: [] },
      { label: "남구", values: ["남구"] },
      { label: "달서구", values: ["달서구"] },
      { label: "달성군", values: ["달성군"] },
      { label: "동구", values: ["동구"] },
      { label: "북구", values: ["북구"] },
      { label: "서구", values: ["서구"] },
      { label: "수성구", values: ["수성구"] },
      { label: "중구", values: ["중구"] },
      { label: "군위군", values: ["군위군"] },
    ],
  },
  {
    label: "인천",
    value: "인천광역시",
    children: [
      { label: "인천 전지역", values: [] },
      { label: "계양구", values: ["계양구"] },
      { label: "남동구", values: ["남동구"] },
      { label: "동구", values: ["동구"] },
      { label: "미추홀구", values: ["미추홀구"] },
      { label: "부평구", values: ["부평구"] },
      { label: "서구", values: ["서구"] },
      { label: "연수구", values: ["연수구"] },
      { label: "중구", values: ["중구"] },
      { label: "강화·옹진", values: ["강화군", "옹진군"] },
    ],
  },
  {
    label: "광주",
    value: "광주광역시",
    children: [
      { label: "광주 전지역", values: [] },
      { label: "광산구", values: ["광산구"] },
      { label: "남구", values: ["남구"] },
      { label: "동구", values: ["동구"] },
      { label: "북구", values: ["북구"] },
      { label: "서구", values: ["서구"] },
    ],
  },
  {
    label: "대전",
    value: "대전광역시",
    children: [
      { label: "대전 전지역", values: [] },
      { label: "대덕구", values: ["대덕구"] },
      { label: "동구", values: ["동구"] },
      { label: "서구", values: ["서구"] },
      { label: "유성구", values: ["유성구"] },
      { label: "중구", values: ["중구"] },
    ],
  },
  {
    label: "울산",
    value: "울산광역시",
    children: [
      { label: "울산 전지역", values: [] },
      { label: "남구", values: ["남구"] },
      { label: "동구", values: ["동구"] },
      { label: "북구", values: ["북구"] },
      { label: "울주군", values: ["울주군"] },
      { label: "중구", values: ["중구"] },
    ],
  },
  {
    label: "세종",
    value: "세종특별자치시",
    children: [
      { label: "세종 전지역", values: [] },
    ],
  },
  {
    label: "경기",
    value: "경기도",
    children: [
      { label: "경기 전지역", values: [] },
      { label: "수원시", values: ["수원시"] },
      { label: "성남시", values: ["성남시"] },
      { label: "고양시", values: ["고양시"] },
      { label: "용인시", values: ["용인시"] },
      { label: "부천시", values: ["부천시"] },
      { label: "안산시", values: ["안산시"] },
      { label: "남양주시", values: ["남양주시"] },
      { label: "화성시", values: ["화성시"] },
      { label: "평택시", values: ["평택시"] },
      { label: "안양시", values: ["안양시"] },
      { label: "시흥시", values: ["시흥시"] },
      { label: "파주시", values: ["파주시"] },
      { label: "김포시", values: ["김포시"] },
      { label: "의정부시", values: ["의정부시"] },
      { label: "광주시", values: ["광주시"] },
      { label: "하남시", values: ["하남시"] },
      { label: "광명시", values: ["광명시"] },
      { label: "군포시", values: ["군포시"] },
      { label: "오산시", values: ["오산시"] },
      { label: "이천시", values: ["이천시"] },
      { label: "안성시", values: ["안성시"] },
      { label: "양주시", values: ["양주시"] },
      { label: "구리시", values: ["구리시"] },
      { label: "포천시", values: ["포천시"] },
      { label: "여주시", values: ["여주시"] },
      { label: "과천·의왕", values: ["과천시", "의왕시"] },
      { label: "가평·양평", values: ["가평군", "양평군"] },
      { label: "연천·동두천", values: ["연천군", "동두천시"] },
    ],
  },
  {
    label: "강원",
    value: "강원특별자치도",
    children: [
      { label: "강원 전지역", values: [] },
      { label: "춘천시", values: ["춘천시"] },
      { label: "원주시", values: ["원주시"] },
      { label: "강릉시", values: ["강릉시"] },
      { label: "동해시", values: ["동해시"] },
      { label: "홍천군", values: ["홍천군"] },
      { label: "속초·양양", values: ["속초시", "양양군"] },
      { label: "태백·삼척", values: ["태백시", "삼척시"] },
      { label: "평창·횡성", values: ["평창군", "횡성군"] },
      { label: "영월·정선", values: ["영월군", "정선군"] },
      { label: "화천·양구·철원", values: ["화천군", "양구군", "철원군"] },
      { label: "인제·고성", values: ["인제군", "고성군"] },
    ],
  },
  {
    label: "충북",
    value: "충청북도",
    children: [
      { label: "충북 전지역", values: [] },
      { label: "청주시", values: ["청주시"] },
      { label: "충주시", values: ["충주시"] },
      { label: "제천시", values: ["제천시"] },
      { label: "진천·음성", values: ["진천군", "음성군"] },
      { label: "보은·옥천·영동", values: ["보은군", "옥천군", "영동군"] },
      { label: "괴산·증평·단양", values: ["괴산군", "증평군", "단양군"] },
    ],
  },
  {
    label: "충남",
    value: "충청남도",
    children: [
      { label: "충남 전지역", values: [] },
      { label: "천안시", values: ["천안시"] },
      { label: "아산시", values: ["아산시"] },
      { label: "서산시", values: ["서산시"] },
      { label: "당진시", values: ["당진시"] },
      { label: "공주시", values: ["공주시"] },
      { label: "보령시", values: ["보령시"] },
      { label: "논산시", values: ["논산시"] },
      { label: "예산·홍성", values: ["예산군", "홍성군"] },
      { label: "부여·서천", values: ["부여군", "서천군"] },
      { label: "청양·계룡", values: ["청양군", "계룡시"] },
      { label: "금산군", values: ["금산군"] },
      { label: "태안군", values: ["태안군"] },
    ],
  },
  {
    label: "전북",
    value: "전북특별자치도",
    children: [
      { label: "전북 전지역", values: [] },
      { label: "전주시", values: ["전주시"] },
      { label: "군산시", values: ["군산시"] },
      { label: "익산시", values: ["익산시"] },
      { label: "정읍시", values: ["정읍시"] },
      { label: "남원시", values: ["남원시"] },
      { label: "김제시", values: ["김제시"] },
      { label: "완주군", values: ["완주군"] },
      { label: "진안·무주·장수", values: ["진안군", "무주군", "장수군"] },
      { label: "임실·순창", values: ["임실군", "순창군"] },
      { label: "고창·부안", values: ["고창군", "부안군"] },
    ],
  },
  {
    label: "전남",
    value: "전라남도",
    children: [
      { label: "전남 전지역", values: [] },
      { label: "여수시", values: ["여수시"] },
      { label: "순천시", values: ["순천시"] },
      { label: "목포시", values: ["목포시"] },
      { label: "광양시", values: ["광양시"] },
      { label: "나주시", values: ["나주시"] },
      { label: "화순군", values: ["화순군"] },
      { label: "해남군", values: ["해남군"] },
      { label: "완도군", values: ["완도군"] },
      { label: "담양·장성", values: ["담양군", "장성군"] },
      { label: "영광·함평", values: ["영광군", "함평군"] },
      { label: "무안·영암", values: ["무안군", "영암군"] },
      { label: "곡성·구례", values: ["곡성군", "구례군"] },
      { label: "고흥·보성", values: ["고흥군", "보성군"] },
      { label: "장흥·강진", values: ["장흥군", "강진군"] },
      { label: "진도·신안", values: ["진도군", "신안군"] },
    ],
  },
  {
    label: "경북",
    value: "경상북도",
    children: [
      { label: "경북 전지역", values: [] },
      { label: "포항시", values: ["포항시"] },
      { label: "경주시", values: ["경주시"] },
      { label: "구미시", values: ["구미시"] },
      { label: "안동시", values: ["안동시"] },
      { label: "경산시", values: ["경산시"] },
      { label: "김천시", values: ["김천시"] },
      { label: "영주시", values: ["영주시"] },
      { label: "영천시", values: ["영천시"] },
      { label: "상주시", values: ["상주시"] },
      { label: "문경시", values: ["문경시"] },
      { label: "칠곡군", values: ["칠곡군"] },
      { label: "울릉군", values: ["울릉군"] },
      { label: "의성·예천", values: ["의성군", "예천군"] },
      { label: "영덕·울진", values: ["영덕군", "울진군"] },
      { label: "청송·영양·봉화", values: ["청송군", "영양군", "봉화군"] },
      { label: "청도·고령·성주", values: ["청도군", "고령군", "성주군"] },
    ],
  },
  {
    label: "경남",
    value: "경상남도",
    children: [
      { label: "경남 전지역", values: [] },
      { label: "창원시", values: ["창원시"] },
      { label: "김해시", values: ["김해시"] },
      { label: "양산시", values: ["양산시"] },
      { label: "진주시", values: ["진주시"] },
      { label: "거제시", values: ["거제시"] },
      { label: "통영시", values: ["통영시"] },
      { label: "사천시", values: ["사천시"] },
      { label: "밀양시", values: ["밀양시"] },
      { label: "함안·창녕", values: ["함안군", "창녕군"] },
      { label: "의령·고성", values: ["의령군", "고성군"] },
      { label: "남해·하동", values: ["남해군", "하동군"] },
      { label: "산청·함양", values: ["산청군", "함양군"] },
      { label: "거창·합천", values: ["거창군", "합천군"] },
    ],
  },
  {
    label: "제주",
    value: "제주특별자치도",
    children: [
      { label: "제주 전지역", values: [] },
      { label: "제주시", values: ["제주시"] },
      { label: "서귀포시", values: ["서귀포시"] },
    ],
  },
];
