-- 레거시 OrderStatus (PENDING, CONFIRMED) → 신규 주문 상태 enum
-- PENDING → PAYMENT_PENDING, CONFIRMED → 그대로

CREATE TYPE "OrderStatus_new" AS ENUM (
  'PAYMENT_PENDING',
  'PAYMENT_COMPLETED',
  'CONFIRMED',
  'PICKUP_PENDING',
  'PICKUP_COMPLETED',
  'USER_RESERVATION_CANCEL_COMPLETED',
  'SELLER_RESERVATION_CANCEL_COMPLETED',
  'REFUND_PENDING',
  'REFUND_COMPLETED',
  'NO_SHOW'
);

ALTER TABLE "orders" ALTER COLUMN "order_status" DROP DEFAULT;

ALTER TABLE "orders" ALTER COLUMN "order_status" TYPE "OrderStatus_new" USING (
  CASE "order_status"::text
    WHEN 'PENDING' THEN 'PAYMENT_PENDING'::"OrderStatus_new"
    WHEN 'CONFIRMED' THEN 'CONFIRMED'::"OrderStatus_new"
    ELSE 'PAYMENT_PENDING'::"OrderStatus_new"
  END
);

ALTER TABLE "orders" ALTER COLUMN "order_status" SET DEFAULT 'PAYMENT_PENDING'::"OrderStatus_new";

DROP TYPE "OrderStatus";

ALTER TYPE "OrderStatus_new" RENAME TO "OrderStatus";
